# Generated by Django 3.1.1 on 2020-09-12 16:49

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='heading1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='heading2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('promo', models.ImageField(blank=True, upload_to='promo/')),
                ('allergene', models.CharField(blank=True, max_length=900)),
                ('zusatzstoffe', models.CharField(blank=True, max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_restaurants', to='main.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat_categories', to='main.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('user_review', models.CharField(blank=True, max_length=500)),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_restaurants', to='main.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='dishe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='recipies/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('num', models.CharField(blank=True, max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique_with=('id',))),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_sub_categories', to='main.sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catoegory_topics', to='main.topic'),
        ),
    ]
