# Generated by Django 3.1.1 on 2020-10-25 21:46

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order_num', models.IntegerField(default=1, verbose_name='Order Nr')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': '3. Categories',
            },
        ),
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Dish')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('number_AZ', models.CharField(blank=True, max_length=100, verbose_name='Nr. A|Z')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from='title', unique_with=('title',))),
                ('order_num', models.IntegerField(default=1, verbose_name='Order Nr')),
            ],
            options={
                'verbose_name': 'Dishes',
                'verbose_name_plural': '5. Dishes',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='recipies/')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': '9. Gallery',
            },
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': '7. Prices',
            },
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('dish_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_dishs', to='main.dish', verbose_name='Dish')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': '6. Sizes and Prices',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slider_image', to='main.image', verbose_name='Promo Image')),
            ],
            options={
                'verbose_name': 'Promo Slider',
                'verbose_name_plural': '10. Promo Slider',
            },
        ),
        migrations.CreateModel(
            name='sub_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('intro', models.TextField(blank=True, max_length=900)),
                ('order_num', models.IntegerField(default=1, verbose_name='Order Nr')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat_categories', to='main.categories')),
            ],
            options={
                'verbose_name': 'Sub Categories',
                'verbose_name_plural': '4. Sub Categories',
            },
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='dishe',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='heading1',
        ),
        migrations.DeleteModel(
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': '1. Restaurants'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': '8. Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topics', 'verbose_name_plural': '2. Topics'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='promo',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dish_access',
            field=models.BooleanField(default=False, verbose_name='Dish Price'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='shisha_law',
            field=models.TextField(blank=True, verbose_name='Shisha Law'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='shisha_price',
            field=models.BooleanField(default=False, verbose_name='Shisha Price'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='shisha_sort',
            field=models.BooleanField(default=False, verbose_name='Shisha Sorts'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slider',
            field=models.BooleanField(default=False, verbose_name='Promo Slider'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='order_num',
            field=models.IntegerField(default=1, verbose_name='Order Nr'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='allergene',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zusatzstoffe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_restaurants', to='main.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='restaurants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_restaurants', to='main.restaurant', verbose_name='Restaurant'),
        ),
        migrations.DeleteModel(
            name='categorie',
        ),
        migrations.DeleteModel(
            name='dishe',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
        migrations.AddField(
            model_name='slider',
            name='restaurants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_restaurants', to='main.restaurant'),
        ),
        migrations.AddField(
            model_name='price',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_cat', to='main.sub_categories', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_image', to='main.image'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_Restaurant', to='main.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_sub_categories', to='main.sub_categories', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='categories',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catoegory_topics', to='main.topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_image', to='main.image'),
        ),
    ]
