# Generated by Django 3.1.1 on 2020-11-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201026_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=128)),
                ('nachname', models.CharField(max_length=128)),
                ('Adresse', models.TextField()),
                ('tel', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
