# Generated by Django 3.1.1 on 2020-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_guestregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestregister',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='guestregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guestregister',
            name='tel',
        ),
        migrations.AddField(
            model_name='guestregister',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestregister',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guestregister',
            name='road',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guestregister',
            name='tel_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guestregister',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
