# Generated by Django 3.1.1 on 2020-11-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201121_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestregister',
            name='adresse',
        ),
    ]
