# Generated by Django 3.1.1 on 2020-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_guestregister_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Guests',
            field=models.BooleanField(default=False, verbose_name='Guests'),
        ),
    ]
