# Generated by Django 3.1.1 on 2020-10-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_auto_20201026_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=400, verbose_name='Page Title')),
                ('detail_html', models.TextField(blank=True, verbose_name='Detail Html')),
            ],
            options={
                'verbose_name': 'AGB',
                'verbose_name_plural': '3. AGB',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=400, verbose_name='Page Title')),
                ('detail_html', models.TextField(blank=True, verbose_name='Detail Html')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': '2. Kontakt',
            },
        ),
        migrations.CreateModel(
            name='data_protection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=400, verbose_name='Page Title')),
                ('detail_html', models.TextField(blank=True, verbose_name='Detail Html')),
            ],
            options={
                'verbose_name': 'Datenschutz',
                'verbose_name_plural': '4. Datenschutz',
            },
        ),
        migrations.CreateModel(
            name='imprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=400, verbose_name='Page Title')),
                ('detail_html', models.TextField(blank=True, verbose_name='Detail Html')),
            ],
            options={
                'verbose_name': 'Impressum',
                'verbose_name_plural': '5. Impressum',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1_text1', models.CharField(blank=True, max_length=100, verbose_name='Slider 1 Text 1')),
                ('slider1_text2', models.CharField(blank=True, max_length=100, verbose_name='Slider 1 Text 2')),
                ('slider1_text3', models.CharField(blank=True, max_length=100, verbose_name='Slider 1 Text 3')),
                ('button1_text', models.CharField(blank=True, max_length=100, verbose_name='Button 1 Text')),
                ('slider2_text1', models.CharField(blank=True, max_length=100, verbose_name='Slider 2 Text 1')),
                ('slider2_text2', models.CharField(blank=True, max_length=100, verbose_name='Slider 2 Text 2')),
                ('slider2_text3', models.CharField(blank=True, max_length=100, verbose_name='Slider 2 Text 3')),
                ('button2_text', models.CharField(blank=True, max_length=100, verbose_name='Button 2 Text')),
                ('welcome', models.TextField(blank=True, verbose_name='Text Below Slider')),
                ('title_text1', models.CharField(blank=True, max_length=400, verbose_name='Title Text 1')),
                ('desc_text1', models.CharField(blank=True, max_length=400, verbose_name='Description Text 1')),
                ('title_text2', models.CharField(blank=True, max_length=400, verbose_name='Title Text 2')),
                ('desc_text2', models.CharField(blank=True, max_length=400, verbose_name='Description Text 2')),
                ('title_text3', models.CharField(blank=True, max_length=400, verbose_name='Title Text 3')),
                ('desc_text3', models.CharField(blank=True, max_length=400, verbose_name='Description Text 3')),
                ('title_text4', models.CharField(blank=True, max_length=400, verbose_name='Title Text 4')),
                ('desc_text4', models.CharField(blank=True, max_length=400, verbose_name='Description Text 4')),
                ('bottom_text', models.CharField(blank=True, max_length=400, verbose_name='Bottom Text')),
                ('img1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_img1', to='main.image', verbose_name='Image 1')),
                ('img2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_img2', to='main.image', verbose_name='Image 2')),
                ('img3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_img3', to='main.image', verbose_name='Image 3')),
                ('img4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_img4', to='main.image', verbose_name='Image 4')),
                ('slider1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_slider1', to='main.image', verbose_name='Slider 1 Image')),
                ('slider2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_slider2', to='main.image', verbose_name='Slider 2 Image')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': '1. Home',
            },
        ),
    ]
